[SCHEMA] Properly cascade folder deletions to imap bookkeeping.
Summary:
If we sync a folder deletion from the remote, we have to cascade it to
ImapFolderInfo and ImapFolderSyncStatus rows, or we get
```
IntegrityError: (IntegrityError) (1048, u"Column 'folder_id' cannot be null")
'UPDATE imapfoldersyncstatus SET updated_at=%s, folder_id=%s WHERE
imapfoldersyncstatus.id = %s' (datetime.datetime(2014, 10, 20, 19, 22, 47,
851225), None, 1524)
```

Note that we already do precisely this cascade for ImapUids.

Test Plan: Regression test added.

Reviewers: kav-ya

Reviewed By: kav-ya

Differential Revision: https://review.inboxapp.com/D633