Fixes T236: (AttributeError) 'int' object has no attribute 'lstrip'
IMAPClient's fetch() parses numeric labels into Python ints/longs.
Therefore convert them to unicode strs.