Fix event parsing to support missing “LAST-MODIFIED” (#356)
I have a bunch of event invites sent from UberConference in my account. They do not have DTSTAMP or LAST-MODIFIED. Our Events table supports null values in that column, so I think we should allow them to be parsed and not blow up.

The exception this fixes is below:

{"traceback": ["Traceback (most recent call last):\n", "  File \"/vagrant/inbox/events/ical.py\", line 391, in import_attached_events\n    part_data)\n", "  File \"/vagrant/inbox/events/ical.py\", line 120, in events_from_ics\n    last_modified = component.get('last-modified').dt\n", "AttributeError: 'NoneType' object has no attribute 'dt'\n"], "account_id": 7, "level": "error", "timestamp": "2016-08-04T23:51:18.138445Z", "greenlet_id": 74350096, "module": "inbox.events.ical:410", "event": "Unhandled exception during message parsing", "state": "initial", "provider": "gmail", "folder": "[Gmail]/All Mail", "logstash_tag": "icalendar_autoimport", "message_id": 89225, "invite": “…